import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:preppilot/features/activities/model/activity_model.dart';
import 'package:preppilot/features/tasks/model/task_model.dart';

class PdfExporter {
  static Future<void> exportAchievementPDF({
    required String userName,
    required List<Activity> activities,
    required List<Task> tasks,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateStr = "${now.day}/${now.month}/${now.year}";

    final completedActivities = activities.where((a) => a.progress == 100).toList();
    final openTasks = tasks.where((t) => t.status != 'completed').toList();
    final overdueTasks = openTasks.where((t) => t.date.isBefore(now)).toList();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("PrepPilot - Achievement Summary", style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18)),
                    pw.Text(dateStr),
                  ],
                ),
              ),
              pw.SizedBox(height: 10),
              pw.Text("Prepared for: $userName", style: pw.TextStyle(fontSize: 14)),
              pw.SizedBox(height: 20),

              pw.Text("Completed Activities", style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
              pw.Divider(),
              pw.TableHelper.fromTextArray(
                context: context,
                data: [
                  ['Name', 'Type', 'Platform'],
                  ...completedActivities.map((a) => [a.name, a.type.toUpperCase(), a.platform]),
                ],
              ),
              pw.SizedBox(height: 24),

              pw.Text("Open Tasks Summary", style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
              pw.Divider(),
              pw.Bullet(text: "Total Open: ${openTasks.length}"),
              pw.Bullet(text: "Overdue: ${overdueTasks.length}"),
              pw.SizedBox(height: 40),

              pw.Footer(
                trailing: pw.Text("Generated by PrepPilot", style: pw.TextStyle(color: PdfColors.grey)),
              ),
            ],
          );
        },
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'achievement_summary.pdf');
  }
}
